version: 2

models:
  - name: stg_products

    description: "Dados de produtos com colunas tratadas, padronizadas e remoção de duplicados"

    columns:

      - name: product_id
        description: "Identificador unico do produto"
        tests:
          - not_null
          - unique   

  - name: stg_products_translation

    description: "Dados de tradução dos produtos com colunas tratadas, padronizadas e remoção de duplicados"

    columns:

      - name: product_category_name
        description: "Categoria do produto em Português"
        tests:
          - not_null

      - name: product_category_name_english
        description: "Categoria do produto em Inglês"
        tests:
          - not_null

