version: 2

models:
  - name: stg_customer

    description: "Dados de clientes com colunas tratadas e padronizadas e remoção de duplicados"

    columns:

      - name: customer_id
        description: "ID do cliente em um pedido "
        tests:
          - not_null
      
      - name: customer_unique_id
        description: "ID único do cliente no marketplace"

        tests:
          - not_null

      - name: state
        description: "Estado do cliente"

        tests:
          - not_null